services:
  - docker
  
before_install:
- docker build -t shields .
- docker run --rm -p 8080:80 --name shields shields


script:
  - gh-badges@1.1.2 start /usr/src/app
  - node server.js

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
