public:
  metrics:
    prometheus:
      enabled: true
      
  cors:
    allowedOrigin: ['http://git.elvns.com/shields']

  rateLimit: false

  handleInternalErrors: false

private:
 gh_token: '69fe4b01650c7e446552a385b62042bf38ca40dc'
