public:
 metrics:
   prometheus:
      enabled: true
      

 cors:
    allowedOrigin: ['http://git.elvns.com/shields', 'http://git.elvns.com/shields']

  redirectUrl: 'http://git.elvns.com/shields/'
