public:
  bind:
    address: '0.0.0.0'
    
  ssl:
    isSecure: true

 cors:
    allowedOrigin: ['http://git.elvns.com/shields', 'http://git.elvns.com/shields']

  redirectUrl: 'http://git.elvns.com/shields/'
